project:
  type: book
  output-dir: public

book:
  title: "Main Missions"
  author: "Rohan Ranshinge"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: side-missions.qmd
        text: Side Missions
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Zero to Hero: Bayesian Stats"
      chapters:
        - zero-to-hero-bsts/PART_I-Bayesian-Statistics/00-Introduction-to-Bayesian-Statistics.ipynb
        - zero-to-hero-bsts/PART_I-Bayesian-Statistics/01-Probability.md
        - zero-to-hero-bsts/PART_I-Bayesian-Statistics/04-Probability-Distributions-Binomial.ipynb
